### ============================
### 🌐 ENDPOINT BASE
### ============================
GET http://localhost:3000/organizacion


### Crear 
POST http://localhost:3000/organizacion
Content-Type: application/json

{
  "nombre": "Mi Empresa S.A.",
  "telefono": 3001234567,
  "direccion": {
    "departamento": "Risaralda",
    "ciudad": "Pereira",
    "comuna": "Centro",
    "barrio": "El Lago",
    "nomenclatura": "Calle 15 #10-25"
  }
}
