# Usa Node 20 LTS
FROM node:20

# Crea el directorio de trabajo
WORKDIR /usr/src/app

# Copia los archivos de configuración primero (para aprovechar la caché)
COPY package*.json ./

# Instala dependencias
RUN npm install

# Copia el resto del código
COPY . .

# Expone el puerto 3000
EXPOSE 3000

# Comando para iniciar el servidor
CMD ["npm", "run", "start"]
